# Generated by Django 2.2.7 on 2020-01-15 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_crossing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestAddBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='имя пользователя')),
                ('name', models.CharField(max_length=200, verbose_name='имя книги')),
                ('author', models.CharField(max_length=200, verbose_name='автор')),
            ],
        ),
        migrations.CreateModel(
            name='RequestBookFront',
            fields=[
                ('user_id', models.IntegerField(verbose_name='id пользователя')),
                ('req_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id запроса')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='книга')),
                ('author', models.CharField(max_length=200, verbose_name='автор')),
                ('requested_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_id', to='book_crossing.RequestBookFront')),
            ],
        ),
    ]
